### PR TITLE
add appache dubbo rpc support

### PR DESCRIPTION
**Pull request by limfriend**
https://github.com/opentracing-contrib/java-specialagent/issues/475

### CODE REVIEW

**Comment by safris** [comment]
Hi @limfriend, thanks for this PR. It seem the build has failed, however, with the message:
```
[ERROR] Failed to execute goal io.opentracing.contrib.specialagent:agentrule-maven-plugin:1.6.0-SNAPSHOT:verify (default) on project opentracing-specialagent: dubbo-1.6.0-SNAPSHOT.jar does not have AgentRunner tests
```
We have a requirement that all rules in the codebase have `AgentRunner` tests. For a guide on usage, please [see here](https://github.com/opentracing-contrib/java-specialagent/tree/master/opentracing-specialagent-api#512-testing).

**Comment by limfriend** [comment]
> Hi @limfriend, thanks for this PR. It seem the build has failed, however, with the message:
> 
> ```
> [ERROR] Failed to execute goal io.opentracing.contrib.specialagent:agentrule-maven-plugin:1.6.0-SNAPSHOT:verify (default) on project opentracing-specialagent: dubbo-1.6.0-SNAPSHOT.jar does not have AgentRunner tests
> ```
> 
> We have a requirement that all rules in the codebase have `AgentRunner` tests. For a guide on usage, please [see here](https://github.com/opentracing-contrib/java-specialagent/tree/master/opentracing-specialagent-api#512-testing).
After add `AgentRunner` test, there is a exception that "
[ERROR] Failed to execute goal io.opentracing.contrib.specialagent:agentrule-maven-plugin:1.6.0-SNAPSHOT:test-compatibility (test-compatibility) on project dubbo: Execution test-compatibility of goal io.opentracing.contrib.specialagent:agentrule-maven-plugin:1.6.0-SNAPSHOT:test-compatibility failed: java.lang.NoSuchFieldException: projectArtifactsCache -> [Help 1]"
What do you suggest about this exception?

**Comment by safris** [comment]
Hi @limfriend, apologies for this error. The code that's resulting in this error is very new (2 days old), so there are still a few bugs. You are receiving this error because of the Maven version you're running. Can you tell me what version you are using to build SpecialAgent? So far, I've tested with Maven 3.5.2 and 3.6.3.

**Comment by safris** [comment]
Hi @limfriend, the issue with the `NoSuchFieldException` should be fixed now.

**Comment by safris** [comment]
Hi @limfriend, thanks for adding the compatibility test specs. Can you tell me what is the reason you had to separate this plugin into 2?

**Comment by limfriend** [comment]
> Hi @limfriend, thanks for adding the compatibility test specs. Can you tell me what is the reason you had to separate this plugin into 2?
the Group/Artifact of dubbo 2.6 is com.alibaba:dubbo, the Group/Artifact of dubbo 2.7 is org.apache.dubbo:dubbo。
it donot work to run  compatibility test when add two passCompatibility. e.g
<passCompatibility>org.apache.dubbo:dubbo:[2.7.1,2.7.4</passCompatibility>
<passCompatibility>com.alibaba:dubbo:[2.6.2,2.6.7]</passCompatibility>

**Comment by safris** [comment]
@limfriend, I reverted the merge for this PR. Here are my reasons:
1. There are no `AgentRunner` test.
1. There are no integration tests.
Once you et these implemented, please open another PR.

**Pull request merged**
