### PR TITLE
create tags from http headers

### LINKED ISSUE #401: How should "http.header." be used
In my fork of specialagent I created the attached patch to add an `http.header.x-uid` .
It works - but is only works with a fork.

If this is considered a useful feature, I'd create a PR.

```
 public abstract class ServletFilterAgentIntercept {
   public static final Logger logger = Logger.getLogger(ServletAgentIntercept.class);
   public static final Map<Object,ServletContext> filterOrServletToServletContext = new HashMap<>();
@@ -47,7 +51,14 @@
       if (filter != null)
         return filter;
 
-      servletContextToFilter.put(context, filter = proxy ? new TracingProxyFilter(GlobalTracer.get(), context) : new TracingFilter(GlobalTracer.get()));
+      List<ServletFilterSpanDecorator> spanDecorators = Arrays.asList(
+          ServletFilterSpanDecorator.STANDARD_TAGS,
+          new ServletFilterHeaderSpanDecorator(Collections.singletonList(
+              new ServletFilterHeaderSpanDecorator.HeaderEntry("x-uid", "x-uid")
+          ))
+      );
+
+      servletContextToFilter.put(context, filter = proxy ? new TracingProxyFilter(GlobalTracer.get(), context) : new TracingFilter(GlobalTracer.get(), spanDecorators, null));
       return filter;
```

### PR DESCRIPTION
**Pull request by zeitlinger**
Fixes #401 

@safris I've also added an `.editorconfig` - so people don't stumble about the 2 space indent, but I can remove it if this doesn't fit for some reason.

### CODE REVIEW

**Comment by safris** [comment]
Hi @zeitlinger, you don't have to worry about the editor config. I review and format all code that ends up a part of the SA codebase, so the config is not really necessary. Either you can remove it, or I'll remove it when I merge this PR.

**Comment by zeitlinger** [comment]
@safris .editorconfig removed and merged with #399

**Comment by safris** [comment]
Hi @zeitlinger, thank you for your contribution to this plugin. I have made a couple changes:
1. I reverted some of the renames you performed. The reason is: We need to keep the `servlet` rule implementation as close as possible to the original version of the `java-web-servlet-filter` from which it was created. This will ensure a lower risk of merging changes into the `servlet` rule that are made to `java-web-servlet-filter` (see #400).
1. I removed the `org.assertj:assertj-core` dependency. This is because it requires jdk1.8, and the plugin is built to support jdk1.7.

**Comment by zeitlinger** [comment]
@safris ok, makes sense - there are a lot of things to consider developing these rules...

**Comment by safris** [comment]
The `assertj` dependency used a class version of jdk8. You are correct that it's a relatively moot point, since it's a test dependency. However, if you attempt to build the SpecialAgent with the jdk version that is an exact appropriate match for what the POM specifies for each plugin, it will fail. The only reason it's passing is because Maven is running in jdk8+, which is able to compile jdk7. If you try to build the plugin with jdk7, it will not work (but it should). The way I've configured Eclipse (the IDE I use), it brings up these issues to my attention.

**Comment by zeitlinger** [comment]
valid point - you could override the jdk version in maven on a module basis - so that maven would fail (then it would not depend on IDE settings)

**Comment by safris** [comment]
In any case, lower coupling is better than higher, even when test frameworks are concerned.

**Pull request merged**
