### PR TITLE
Match service name

### LINKED ISSUE #437: Question: How to add tags to all spans?
Hello,

First of all, thanks for contributing this excellent library, and apologies if this question is better suited to a different forum - please feel free to redirect me if that is the case.

Context: I'm currently using the Jaeger tracing plugin, which uses the concept of a "Process" object to house tags that are common across all spans in a trace (e.g. `service_name`). However, I'm also using a downstream component (Honeycomb) which expects `the service_name` tag to be present on each individual span, and doesn't recognise the "Process" object.

Question: Is it possible to somehow inject a piece of code into the specialagent which can decorate each span (regardless of specific instrumentation plugin) and add some tags before sending?

Looks like #415 might be relevant.

Many thanks in advance!

### PR DESCRIPTION
**Pull request by zeitlinger**
Fixes #437 

Based on #428 

Notes:
@safris I've described [global rules](https://github.com/opentracing-contrib/java-specialagent/compare/zeitlinger-customizable-span...zeitlinger:match-service-name?expand=1#diff-8fbc32011d948ccaad5e4559e4463f81R203), because they are needed by #437 - but I haven't implemented them - since this is in the "glue" part that you wanted to implement. 

Update: Support for global rules is added - see the [test case](https://github.com/opentracing-contrib/java-specialagent/blob/10db3a90fded2371fe04c13b211f5e8ea548625f/opentracing-specialagent-util/src/test/java/io/opentracing/contrib/specialagent/adaption/AdaptionRuleParserTest.java#L21-L27)

### CODE REVIEW

**Comment by safris** [comment]
Hi @zeitlinger, I just saw this PR. It seems I've made some changes that make this merge challenging. Would you be able to adapt your changes to the latest modifications?

**Comment by zeitlinger** [comment]
> Hi @zeitlinger, I just saw this PR. It seems I've made some changes that make this merge challenging. Would you be able to adapt your changes to the latest modifications?

done

**Comment by safris** [comment]
Hi @zeitlinger, I have merged this into the `zeitlinger-customizable-span` branch, and here is my feedback:

1. It took me a while to figure out the logic in `AdaptionRuleParser` re `globalRules`. Would it be possible if you could make this code clearer? I mean, it is really cryptic! Passing `new AdaptionRule[0]` into `parseRules`... This code resembles a "hack", and we need to do this right before I'll integrate into SpecialAgent core.
1. The `TracerIntrospector` mentions Jaeger and LightStep, which is illegal. No mention of specific tracer service providers is allowed, as SpecialAgent is a pluggable architecture. This code also resembles a "hack", because it seems you're trying to "hack" something for 2 specific tracers. And what if it's WaveFront tracer? Or the OTel Tracer bridge? MockTracer? If the user wants to add a `serviceName` tag to all spans, then he must specify this `serviceName` explicitly in the config.

Before we move forward, I think it would be good to take a step back and write down the spec for the functionality of this "Adaptive Spans" work. To guide this spec writeup, here are the questions to come to mind:
1. Configuration: What are the dimensions of configuration allowed by the JSON spec? i.e. The config allows specification of the adaptation of X, Y, Z. You have this written out in the README, but let's group these "dimensions" together.
1. Configuration: What is the range for configuration of each of the dimensions in (1)? i.e. For blacklist, it's either **true** or (**false** or **not present**); for transformation, it's a simple string value? What's the range of the value? Can you express it with a regex? Also, for transformation, we have regex -- what is the range of the regex? For global adaptations, what is the range?
1. Implementation: What are the phases the implementation goes through on startup? As in:
   a. Parse configuration into `AdaptionRule` objects.
   b. Validate configuration...
   c. Instantiate `AdaptiveSpanBuilder`, `AdaptiveTracer`, etc.
1. Implementation: What are the phases the implementation goes through during runtime? As on call to `Span.setTag`, `Span.log`, etc:
   a. Iterate through all rules, attempting to match rule's criteria.
   b. On match, iterate through "outputs", and apply transformation.

You distinguish between "processing" and "setting". Can you elaborate on this? There's some hidden complexity here, which gives me concern because such situations are more prone to bugs.

Also, I'm still confused as to what is going on in `AdaptiveSpanBuilder`, because it is itself `Adaptive`, and it has a member `Adaptive` as well.

`AdaptiveSpan.newLogFieldAdapter()` is being called for each call to `Span.log()`. I can see that doing this allows you to reuse some of the abstractions you created. But, you have to instantiate a new object each time, which is not good. Fundamentally, this should not be necessary. However, in this situation, the architecture requires a new instance, which tells me that the architecture needs to change. It all comes down to the architecture of "having the work be done **to the object**" instead of "having the object do the work **onto itself**".

**Comment by zeitlinger** [comment]
> 1. It took me a while to figure out the logic in `AdaptionRuleParser` re `globalRules`. 

I created #441 - hope that makes it clearer

> 2. The `TracerIntrospector` mentions Jaeger and LightStep, which is illegal...

So then we could rename `serviceName` to `span` or `global` - and remove the part that reads the service name - you can still use the output part with a provided value. I cannot think of any other option right now.

> 1. Configuration: What are the dimensions of configuration allowed by the JSON spec? i.e. The config allows specification of the adaptation of X, Y, Z. You have this written out in the README, but let's group these "dimensions" together.

If want to look at this from a spec point of view, the README is pretty useless.

An input i can be transformed into 0..n outputs o, where
- i = (operationName | log event | log fields | tag | serviceName)
- o = (operationName | log event | log fields | tag)

> 2. Configuration: What is the range for configuration of each of the dimensions in (1)? i.e. For blacklist, it's either **true** or (**false** or **not present**); 

see above

> for transformation, it's a simple string value? 

- for regex matches replacement, it's string
- otherwise it's string, number, or boolean

> What's the range of the value? Can you express it with a regex? Also, for transformation, we have regex -- what is the range of the regex? For global adaptations, what is the range?

what do you mean by that?

> 3. Implementation: What are the phases the implementation goes through on startup? As in:
>    a. Parse configuration into `AdaptionRule` objects.
>    b. Validate configuration...
>    c. Instantiate `AdaptiveSpanBuilder`, `AdaptiveTracer`, etc.

yes, those are the phases

> 4. Implementation: What are the phases the implementation goes through during runtime? As on call to `Span.setTag`, `Span.log`, etc:
>    a. Iterate through all rules, attempting to match rule's criteria.
>    b. On match, iterate through "outputs", and apply transformation.

yes

> You distinguish between "processing" and "setting". Can you elaborate on this? 

I think I used "processing" for rules, nothing more and maybe not the best choice.

> There's some hidden complexity here, which gives me concern because such situations are more prone to bugs.

I'm quite confident regarding the bugs - since I've checked the test coverage is very good.
Regarding the complexity I get the feeling that our coding styles are a bit different - maybe you are just not used to it.

> Also, I'm still confused as to what is going on in `AdaptiveSpanBuilder`, because it is itself `Adaptive`, and it has a member `Adaptive` as well.

I believe you introduced that during a refactoring - see https://github.com/opentracing-contrib/java-specialagent/pull/415#issuecomment-587488179 - if not, I'll go back and try to figure out why I did it.

> `AdaptiveSpan.newLogFieldAdapter()` is being called for each call to `Span.log()`...

We need to create a new instance of `private Map<String,Object> fields` in `LogFieldAdapter` - this is the only reason.

**Pull request merged**
