### PR TITLE
customizable span

### PR DESCRIPTION
**Pull request by zeitlinger**
PR for #407 

Features
1. blacklisting of tags, fields in log entries or entire log entries
2. transform values (tag values, log field values or log events)
3. transform log to tag or tag to log
4. for a syntax, see [README](https://github.com/zeitlinger/java-specialagent/blob/customizable-span/opentracing-specialagent-util/src/main/java/io/opentracing/contrib/specialagent/tracer/README.md)

Still missing 

- [ ] [Integration](https://github.com/opentracing-contrib/java-specialagent/pull/415#issuecomment-586982431) into `AgentRule` by @safris

### CODE REVIEW

**Comment by safris** [comment]
Hi @zeitlinger, thanks for submitting this PR. The scope of this work is bigger than I expected. The functionality to blacklist tags, fields or entire logs is a good feature. Transformation of values, however, seems a bit controversial to me, because this functionality can become very complex very fast. If you keep the complexity low, then you'll only be able to make "linear transformations" -- i.e. renaming tags or replacing values with static values. With this limited "linear transformation" approach, it begs the question: is even this limited functionality worth implementing? Do you have a use-case that's encouraging your development of this feature? Similar question re log<-->tag transformations.

**Comment by zeitlinger** [comment]
I implemented the tag to log transformation for one rule in my fork in a
hard coded way, based on observing traces for the first real service.

In this case, redis statements are logged instead of tagged - or
blacklisted based on a single system property.

It later occurred to me that having a prefix of the statement as a tag (in
the original tag) would be very helpful. Hence the multiple output
functionality and the value transformation.

All the features are derived from this use case.

**Comment by zeitlinger** [comment]
@safris work is done from my side - it did take more time than I thought - but I hope it's worth the effort.

Some notes:

As agreed, I left the "glue" part to you
1. Read `-Dsa.customizableTracer=<path to json file>`
2. [parse](https://github.com/opentracing-contrib/java-specialagent/pull/415/files#diff-90e1f590b7f2fb2ed6d96b5331005b0fR19) the configuration 
3. provide a [CustomizableTracer](https://github.com/opentracing-contrib/java-specialagent/pull/415/files#diff-8877ca25ea48eee228ca08f36d342901R14) if an entry was found in the map from the previous call
4. implement [getTracer](https://github.com/opentracing-contrib/java-specialagent/issues/407#issuecomment-585245399)

I'm concerned about classpath conflicts when using a common json parser (such as Gson), so I included a very small one - [nanojson](https://github.com/mmastrac/nanojson).

**Comment by safris** [comment]
Hi @zeitlinger, good work! It's a significant number of files modified, so it will take me a bit to review. I've merged this PR into [a dedicated branch](https://github.com/opentracing-contrib/java-specialagent/tree/zeitlinger-customizable-span) in SpecialAgent's codebase, and we can sync there. Thank you for this.

**Comment by safris** [comment]
Hi @zeitlinger, I have done my first round of review and edits [here](https://github.com/opentracing-contrib/java-specialagent/commit/8c93530572fd9f7fe118410003ccb49fb0716e37). For this round, my focus was:
1. Remove functional coupling between JSON files and the code. You had enums coupled to the tag names.
1. Remove `SpanRuleValidator`, as all of its functionality fits in `SpanRuleType`.
1. Fix `SpanRuleParserTest`, as it would pass regardless of success or failure.

I'm estimating further review will take a couple more days. Though you've done a good job with the tests you've provided, my concern is that your choice of JSON as the spec format introduces multidimensional error space due to its nestable nature. So far, SpecialAgent has kept all of its configuration to "properties" format (which is a one-dimensional error space). The choice of "properties" format has allowed SpecialAgent to keep its functionality regarding configuration as simple as could be, thus resulting in low potential bugs, and insulating from future complexity creep.

**Comment by zeitlinger** [comment]
> 1. Remove functional coupling between JSON files and the code. You had enums coupled to the tag names.

is this referring to the tests?

> 2. Remove `SpanRuleValidator`, as all of its functionality fits in `SpanRuleType`.

do you mean `SpanRuleParser` instead of `SpanRuleType`?

> 3. Fix `SpanRuleParserTest`, as it would pass regardless of success or failure.

Not sure I understand what you mean. What method are you referring to?

> choice of JSON as the spec format 

Yes, I understand and share the concern. I've thought about ways to flatten the tree structure into properties - but haven't found a satisfactory solution so far. This was my thinking so far:

```
sa.customizableTracer.jedis.0.type = tag
sa.customizableTracer.jedis.0.key = db.statement
sa.customizableTracer.jedis.0.output.0.type = tag
sa.customizableTracer.jedis.0.output.1.type = log
```

**Comment by zeitlinger** [comment]
I saw in your commit that you already fixed some of the addressed issues, 1 - 3.

My comments
1. The intention `completeInvalidJson` and `oneRuleInvalidJson` was to test the failure boundaries - i.e. that an error in one plugin does not affect others and that an error in the rules doesn't affect the specialagent.
2. You inserted some `final`s in prose (README), which was not intended I think.

**Comment by safris** [comment]
Hi @zeitlinger, I've done some refactoring, and there is [one part of the code](https://github.com/opentracing-contrib/java-specialagent/blob/zeitlinger-customizable-span/opentracing-specialagent-util/src/main/java/io/opentracing/contrib/specialagent/tracer/CustomizableTracer.java#L42-L46) that I think is incorrect. I had to add the `clear()` calls to have your tests pass. I believe the tests are incorrect in expecting that `clear()` is called. This code is present in lieu of a reduction of complexity, whereby I integrated the `OperationNameCustomizer` directly into the `CustomizableTracer`.

**Comment by zeitlinger** [comment]
I believe this is a result of your refactoring - but I'll double check to
make sure.
It looks like you introduced state into the customizable tracer (tags,
logs), which is not thread safe.

**Comment by safris** [comment]
Hi @zeitlinger, you were right:
> I believe this is a result of your refactoring...
It was indeed a result of my refactoring. I guess I got confused by the pattern you were using. I've refactored this section, and have taken a step further to unwind the mix of OO and functional patterns you put together -- in order to make the code clearer. I've converted the functional patterns in `SpanRules` into OO patterns in `SpanCustomizer`. If you have any comments or concerns, please don't hesitate!

**Comment by zeitlinger** [comment]
@safris I think we had a good time sharing yesterday - when I woke up, I saw your comment :smile: 

Thanks again for the fast help!

After I tried a couple if designs I decided against using implementation inheritance, because I got confused by it. 
The current version has something similar but I guess it's a matter of taste.

```java
public class CustomizableSpanBuilder extends SpanCustomizer implements Tracer.SpanBuilder {
  private final SpanCustomizer customizer;
  private final Tracer.SpanBuilder target;

  public CustomizableSpanBuilder(final String operationName, final Tracer target, final SpanRules rules) {
    super(rules);
    this.customizer = new SpanCustomizer(rules) {
```

Today I started to add a test that makes sure that we're not doing excessive list and map allocations - but this is not finished yet. I think I'll open a second PR that goes against the new integration branch once it's ready.

**Comment by safris** [comment]
Hi @zeitlinger, I have applied a bit of focus on the list/map allocation question, and I agree that a test would be nice to have. Could I ask you for a couple things:
1. Can you switch to use the [zeitlinger-customizable-span](https://github.com/opentracing-contrib/java-specialagent/tree/zeitlinger-customizable-span) branch for your changes? The codebase has evolved pretty significantly since this original PR.
1. I noticed you added `bytebuddy` dependency to `opentracing-specialagent-util` -- what is your intended use of ByteBuddy for testing?

**Comment by zeitlinger** [comment]
> Can you switch to use the [zeitlinger-customizable-span](https://github.com/opentracing-contrib/java-specialagent/tree/zeitlinger-customizable-span) branch for your changes? 

yes, currently doing that

> I noticed you added `bytebuddy` dependency to `opentracing-specialagent-util` -- what is your intended use of ByteBuddy for testing?

No, it was simply a fix which made mockito work.

Here are the new things I found:
1. `CustomizableSpan` reuses `logFieldCustomizer`
1.1 this can cause issues with multiple threads
1.2 the `fields` buffer in LogFieldCustomizer is not cleared
2. Why do you prevent io.opentracing.contrib.specialagent.tracer.CustomizableSpan#setOperationName to be called multiple times (there was no test case for that)?

**Comment by zeitlinger** [comment]
@safris I created #428 for the object allocations test and to address (1) from the previous comment.

**Comment by safris** [comment]
Hi @zeitlinger, I have just committed my changes to Customizable Span module. I apologize for making so many changes, but at the end of the day it's code that I would be at the front line to support. Generally speaking, what I'm doing is this: The coding patterns that you use resemble more of functional patterns than OO. Static methods, passing function objects, and uninstantiable classes are things you'd encounter in functional paradigms. My challenge with functional patterns is that they lead to increased coupling and deceased cohesion. It is increased coupling because you end up with multiple classes involved in a single intention -- multiple classes whose static methods are being called in particular sequence in order to achieve a result. It is decreased cohesion because the logic for a single intention is spread across a wide area -- when you look at any one part of the wide area, it's difficult to get a grasp of the underlying intention. Therefore, I've been refactoring your code to OO patterns, in order to reduce coupling and increase cohesion. My desire is to make the code clear to understand when anyone would look at it.

After some deep thinking, I decided to change the underlying word that defines this module. I've changed it from `customizable` to `adaptive`. The word `adapt` seems to give us better adverb, noun, adjective, etc word forms that make the code easier to follow.

Before, the `SpanCustomizer` was being used as both a consumer and a producer for the `LogEvent` and `LogField`, but nowhere else. Now, there is a distinction between an `Adapter` and an `Adaptive`.

I've converted `AdaptionRule` (formerly `SpanRule`) into an abstract class with a generic type, which cleanly allows us to implement a corresponding `match()` method via polymorphism.

I have removed the `protected` keyword you added, simply because there is no intention of allowing others to subclass any of these classes we're working on right now.

As far as the JSON config spec is concerned, we should create tests to catch all ways a used could make an invalid config (structurally invalid, i.e. a misplaced/invalid property/object/array).

Lastly, once we get this integrated to SpecialAgent, I'm going to propose this work to [opentelemetry-auto-instr-java](https://github.com/open-telemetry/opentelemetry-auto-instr-java/) (if you don't mind, of course -- and you are welcome do so yourself too if you want).

**Comment by zeitlinger** [comment]
> I apologize for making so many changes

No problem - I don't mind :smile: 

> As far as the JSON config spec is concerned, we should create tests to catch all ways a used could make an invalid config 

I've added [test cases](https://github.com/opentracing-contrib/java-specialagent/pull/439/commits/10db3a90fded2371fe04c13b211f5e8ea548625f)

> Lastly, once we get this integrated to SpecialAgent, I'm going to propose this work to [opentelemetry-auto-instr-java](https://github.com/open-telemetry/opentelemetry-auto-instr-java/) (if you don't mind, of course -- and you are welcome do so yourself too if you want).

yes, that sounds great - I trust you to handle it in the best possible way (copying the code vs. extracting it as a separate project).

**Comment by safris** [comment]
This PR has been superseded by #479.

**Pull request closed without merging**
