### PR TITLE
activates mule jdk11 itests (#405)

### PR DESCRIPTION
**Pull request by jam01**
see https://github.com/opentracing-contrib/java-specialagent/issues/405

### CODE REVIEW

**Comment by safris** [comment]
Hi @jam01, I got the build for SpecialAgent working, and it looks like Mule for jdk11 is still failing.

**Comment by jam01** [comment]
Hey @safris I see the build failing. I'm not sure I'll find time to dig in until next week however.

**Comment by jam01** [comment]
It seems I don't have permissions to re-run this. Do you mind @malafeev :)

**Comment by malafeev** [comment]
@jam01 yes, I can rerun

**Comment by malafeev** [comment]
@jam01 could you sync master branch with this PR branch?

**Comment by jam01** [comment]
Yes, one min...

**Pull request merged**
