### PR TITLE
fix instructions on .enable/.disable

### PR DESCRIPTION
**Pull request by zeitlinger**
alternatively, the implementation could be changed to match the documentation, but that would be more work.

### CODE REVIEW

**Comment by zeitlinger** [comment]
> @zeitlinger, these changes are not necessary. Specifying:
> `sa.instrumentation.plugin.*.disable`
> has the same effect as specifying:
> `sa.instrumentation.plugin.*.disable=true`

For `.disable`, you're right.
For `.enable`, it doesn't work, because `Boolean.parseBoolean("")` is `false`.

Therefore, I added `true` and `false` everywhere.

```
        else if (key.indexOf(".enable", 27) != -1)
          instruPluginNameToEnable.put(key.substring(26, key.length() - 7), Boolean.parseBoolean(value));
        else if (key.indexOf(".disable", 27) != -1)
          instruPluginNameToEnable.put(key.substring(26, key.length() - 8), "false".equals(value));
```

**Comment by safris** [comment]
@zeitlinger, thank you for catching this. It was my oversight, and I have just pushed a change to fix this. Specitying `.enable` (without `=true`) [will work now](https://github.com/opentracing-contrib/java-specialagent/commit/63d71383ff6c04ed4c533f28f309a8107a037173).

**Comment by zeitlinger** [comment]
> @zeitlinger, thank you for catching this. It was my oversight, and I have just pushed a change to fix : this. Specifying `.enable` (without `=true`) [will work now](https://github.com/opentracing-contrib/java-specialagent/commit/63d71383ff6c04ed4c533f28f309a8107a037173).

OK, that was actually quite easy :smile: 

I think I'd add a unit test that actually tests with `""`.

**Comment by safris** [comment]
@zeitlinger, yes, you're absolutely right. Many of the init patterns for SpecialAgent (the ones in the `SpecialAgent` class) were developed very hastily, and there is a lot left to be desired when it comes to tests. I have created an issue (#342) to bolster the tests for SpecialAgent's init patterns. I'll close this PR later today after the release of SpecialAgent v1.5.5.

**Comment by safris** [comment]
Closing this as of release of [v1.5.5](https://github.com/opentracing-contrib/java-specialagent/milestone/2).

**Pull request closed without merging**
