### PR TITLE
Adds mule 4 instrumentation

### PR DESCRIPTION
**Pull request by jam01**
Hey @safris , I'm opening this PR a bit prematurely looking for some confirmation that the general structure of the plugins aligns with the project. 

I'm missing tests here for now, entirely because most of the development has been exploratory. Now that I've got something basically working I'll move on to getting some coverage and then possibly some refactoring.

On the multiple plugins... 
mule-4-http-service instruments an artifact that is independent to the core mule runtime. 
The other two are logically separate but in practice they evolve and are released together, with the same version. 

So I wonder if there's some way you'd rather group those two, or if all mule 4 plugins should have a parent rule module somewhow.

What do you think?

### CODE REVIEW

**Comment by jam01** [comment]
Hey @safris couple of things for when you get a chance:

1. Any thoughts on the the structure of the multiple mule 4 plugins?
2. Rule tests are currently failing JDK 11 runs with `java.lang.AssertionError: Method "clearTestCaseName" should be executed in URLClassLoader`, you can see the [travis details](https://travis-ci.org/opentracing-contrib/java-specialagent/builds/633925914). Is there anything I should be doing differently?
3. I'm also trying to create an integration test but I'm running into an obstacle, I have to create a mule application first as a separate artifact which then I have to use in the actual integration test. So I wonder how you would like for me to structure the modules so that I can package a submodule without including it in the ITest runs? Here's [the app](https://github.com/jam01/java-specialagent/blob/master/test/mule-4.2.2/test-app/pom.xml) and this is how I'm [copying it over](https://github.com/jam01/java-specialagent/blob/master/test/mule-4.2.2/container-itest/pom.xml#L70) to the runtime but it currently wouldn't be automatically built. Maybe just an extra command for travis?

**Comment by safris** [comment]
Hi @jam01, these are all great questions. Here is my input:
1. Regarding the structure of the plugins: I cloned your PR and looked at the structure, and see that you have 3 plugins. Do the plugins function independently? If yes, then this structure is good. If no (i.e. there is some dependency between two plugins, for instance), then those 2 plugins would have to be merged into one plugin.
1. I looked into this error, and can see it's due to the complexity of your test inheriting from `AbstractMuleTestCase`. It's interesting that the test passes on jdk1.8, but not on jdk11. This tells me that there is some difference with regard to class loading order between the two JDKs. Best thing you should do is simply to specify `@AgentRunner.Config(isolateClassLoader = false)` on the test class.
1. This is a really interesting obstacle! It's a completely valid use-case, and I'm realizing the SpecialAgent doesn't yet have anything like this. I have two patterns that come to mind:
   1. The modules under the `test` path (the integration test modules) all implement their tests in `src/test/...`, and the `src/main` is absent. You could import your Mule test application into the `src/main` path(s). The "pro" with this pattern is that it fits with the existing pattern of other integration tests. The "con" with this pattern is that you would have to copy your Mule test into the `src/main` of each integration test module you write. This is not scalable, because it may happen that in the future you'd write a different integration test for Mule 4.9, for example.
   1. We can also invent a modification to the module layout/pattern in `test`. We can add another directory layer -- i.e. `test/mule/`. There, you can add a module that only has `src/main`, and is the Mule test app. Then, you implement your integration test modules next to your `mule-test-app` module. I think this pattern works best, and I don't see any reason why it wouldn't work with the current SpecialAgent build architecture.

**Comment by jam01** [comment]
OK something seemingly super strange... The JDK 8 run passes, but the JDK 11 fails because it can't retrieve a maven dependency... What?

https://travis-ci.org/opentracing-contrib/java-specialagent/jobs/634500442

**Comment by safris** [comment]
@jam01, yes, we're seeing this for SpecialAgent too: #336.

**Comment by jam01** [comment]
So JDK 11 runs for the mule integration test were failing on CI, but were passing locally. So I setup a github actions CI just for mule 4 on openjdk 11 and it is passing.

https://github.com/jam01/java-specialagent/commit/1cc54033e1b6a0a7fc584458ee07ff4cc6ba3c93/checks?check_suite_id=395890284

You may want to click "Raw logs", the main page sometimes crashes for me. The logs on FINER are reaaaally long (they actually crash Travis)

So I'm not sure why they fail on Travis CI. The JDK is a couple of minor revisions newer 11.0.5 vs 11.0.2. I'm not sure what version maven is. And from reading https://github.com/opentracing-contrib/java-specialagent/issues/312 it seems it's important that the version of ubuntu is not Trusty, but 18.04.3 LTS (Bionic Beaver)

What do you suggest? Do I _need_ Trusty? I tried replicating it in a container but couldn't quickly figure out how to install JDK 11 on it, seems only 1.8 is supported in the standard package repos.

**Comment by safris** [comment]
Sounds good @jam01. Let's disable J11 for now, and try again when you're ready for review and merge.

Re Travis CI: Travis CI is literally a nightmare! I cannot even begin to tell you how much time I've spent trying (and failing) to fix it for SpecialAgent. Last week I tried to replace Travis CI with GitHub Actions, but I ran into [other issues](https://github.com/opentracing-contrib/java-specialagent/issues/312). Next week, I will try to [migrate to Circle CI](https://github.com/opentracing-contrib/java-specialagent/issues/344).

**Comment by jam01** [comment]
Rebased to include the test module changes, but was having an issue where spring mvc tests were failing, then pulled latest today and now it seems pulsar tests just run forever.... This was all local, so maybe the ci run will be different.

**Comment by safris** [comment]
Hi @jam01, hmmm... Let's see what Travis CI says.

**Comment by jam01** [comment]
Yeah I keep getting the following locally: 
```
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ pulsar-client ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running io.opentracing.contrib.specialagent.rule.pulsar.client.PulsarClientTest
`isolateClassLoader=false`
All attempts should be taken to avoid setting `isolateClassLoader=false`
io.opentracing.contrib.specialagent.rule.pulsar.client.PulsarClientAgentRule
.==============================================================.
|                    Static Deferred Attach                    |
|                        Enabled: false                        |
|==============================================================|
' 0 deferrers were detected
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'log4j2.debug' to show Log4j2 internal initialization logging.
11:34:13.160 [main] ERROR org.apache.bookkeeper.bookie.Journal - Problems reading from /tmp/bk0test1696659976848665793/current/lastMark (this is okay if it is the first time starting this bookie
11:34:13.537 [main] ERROR org.apache.bookkeeper.bookie.Journal - Problems reading from /tmp/bk1test2281801088265504882/current/lastMark (this is okay if it is the first time starting this bookie
11:34:13.595 [main] ERROR org.apache.bookkeeper.bookie.Journal - Problems reading from /tmp/bk2test6098261866137987411/current/lastMark (this is okay if it is the first time starting this bookie
11:34:20.540 [pulsar-41-4] ERROR org.apache.pulsar.common.stats.JvmMetrics - Failed to collect GC stats: java.lang:type=GarbageCollector,name=G1 Young Generation
11:34:32.651 [bookkeeper-io-52-15] ERROR org.apache.bookkeeper.proto.PerChannelBookieClient - Could not connect to bookie: [id: 0xee55c045, L:/192.168.1.10:60880]/23.217.138.107:8881, current state CONNECTING : 
io.netty.channel.ConnectTimeoutException: connection timed out: a23-217-138-107.deploy.static.akamaitechnologies.com/23.217.138.107:8881
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$2.run(AbstractEpollChannel.java:571) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:125) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
11:34:32.642 [bookkeeper-io-52-11] ERROR org.apache.bookkeeper.proto.PerChannelBookieClient - Could not connect to bookie: [id: 0xae5adde3, L:/192.168.1.10:60860]/23.217.138.107:8881, current state CONNECTING : 
io.netty.channel.ConnectTimeoutException: connection timed out: a23-217-138-107.deploy.static.akamaitechnologies.com/23.217.138.107:8881
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$2.run(AbstractEpollChannel.java:571) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:125) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]

```

**Comment by safris** [comment]
Hi @jam01, it looks like the Mule test is still failing with:
```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.Exec.main(Exec.java:26)
Caused by: java.lang.AssertionError: ERROR: java-grizzly-ahc span not found
	at io.opentracing.contrib.specialagent.test.Mule4ContainerITest.checkSpans(Mule4ContainerITest.java:104)
	at io.opentracing.contrib.specialagent.test.Mule4ContainerITest.testHttpFlow(Mule4ContainerITest.java:66)
	at io.opentracing.contrib.specialagent.test.Mule4ContainerITest.main(Mule4ContainerITest.java:41)
	... 5 more
```

To make your testing faster, you can move:
```
  - name: "Mule 4 [openjdk8]"
    stage: test
    jdk: openjdk8
    install: true
    script:
    - 'mvn -B install --file test/mule/mule-4-app/pom.xml &&
    mvn -B -P test -pl test/mule -Dsa.log.level=FINE -amd install'
```
to the top of `.travis.yml`.

**Comment by jam01** [comment]
Oh! The grizzly http-client sa.plugin name changed!

**Comment by safris** [comment]
@jam01, that's my fault! 😬

**Comment by jam01** [comment]
I can't explain why this is failing now...

**Comment by jam01** [comment]
This seems finally ready :')

**Comment by safris** [comment]
Hi @jam01, sorry to keep throwing monkey wrenches into your tests. Could you rebase to origin/master? I've just fixed some core bugs that were resulting in integration test failures.

**Comment by jam01** [comment]
You got it : ) give me a couple of hours...

**Comment by jam01** [comment]
rebased :)

**Comment by jam01** [comment]
@safris have there been any big changes to jdbc rules?

**Comment by safris** [comment]
Hey @jam01, so your latest merge is failing the `mule` test. Here's a link to the [raw log](https://api.travis-ci.org/v3/job/647186777/log.txt).

**Comment by safris** [comment]
Hi @jam01, I have figured out the problem and have fixed it. This PR is now merged. I have added 3 new issues related to the Mule Rule: #404, #405, #406.

**Comment by jam01** [comment]
Thanks, Seva! Already answered some and will keep digging.

**Comment by ckho** [comment]
Currently, the instrumentation supports only Mule 4.2.2 or above. Is it possible to make it compatible with 4.1.x (or in specific, 4.1.6)?

**Comment by jam01** [comment]
Hey @ckho , I've not had much time to continue work on this, but I should have some soon. 4.1.6 is not officially supported, but it might work. If you can create an integration test for 4.1.6 we might see what issues come up if any.

**Pull request merged**
