### PR TITLE
clean up adaptive span builder

### PR DESCRIPTION
**Pull request by zeitlinger**
Relates https://github.com/opentracing-contrib/java-specialagent/pull/441#issuecomment-591735231

### CODE REVIEW

**Comment by safris** [comment]
Hi @zeitlinger, thanks for this modification. It looks better now! I have taken a step forward here as well, and have removed passing of functions with regard to `AdaptionRule.match()`.

Here are the outstanding things we need to figure out:
1. We can't mention LightStep or Jaeger re the `serviceName`.
1. `AdaptiveSpan.newLogFieldAdapter()` is called for every call to `Span.log()`.

**Comment by zeitlinger** [comment]
Have you seen my comments on both issues?

**Comment by safris** [comment]
Hi @zeitlinger, apologies, I may have missed something. We're a bit scattered here re this work, for which I am to blame. Could you point me to the comment you're referring to? Also, let's agree to make our comments in #407 regarding all PRs related to this work.

**Comment by zeitlinger** [comment]
The comment is https://github.com/opentracing-contrib/java-specialagent/pull/439#issuecomment-591652960

**Pull request merged**
