### PR TITLE
Split CXF rules into server part and client part.

### PR DESCRIPTION
**Pull request by jianshaow**
Split CXF rules into server part and client part in case they can be enabled or disabled separately. Some cases, servlet tracing filter will be used instead of CXF server tracing.

### CODE REVIEW

**Comment by safris** [comment]
Hi @jianshaow, can CXF be sprit into 2 rules: `cxf-server` and `cxf-client`?

**Comment by jianshaow** [comment]
@safris, JAX-WS spec is a kind of old style web service, sometimes we don't use it at all, 4 rules can provide fine grain options for developers, after all, every single rule costs application launch time. Anyway, I just think it would be nice to have, I'm OK with just 2 rules if you insist. what do you think?

**Comment by safris** [comment]
Hi @jianshaow, you are correct regarding your concern of "every single rule costs application launch time". I have a couple issues regarding this (#492 #524). For JAX-WS, I believe the first question is:
1. Is JAX-WS client and server split into different JARs?
1. If yes, then is there a clear line between the JAX-WS client and server encapsulations? If there is a clear line, then it would make sense to split the instrumentation for client and server into separate rules. This is because the loading time of the rules would be close to the same if they are split apart or are together. But, if they are split apart, then it would give users an easier way to manage which rules to load.
1. If JAX-WS does not have clear separation between the client and server (i.e. they are not individually encapsulated), then it would make sense to keep the entire instrumentation for JAX-WS in a single rule.

**Comment by jianshaow** [comment]
Hi @safris, sorry, I just misunderstood what you meant, I though you disagree splitting the 2 rule classes into  4. Just now I realized that you are saying splitting a rule project into 2, right? Confusing me "rule" the term. That would be a right thing to do, I just do it.

**Comment by safris** [comment]
Hi @jianshaow, no no... I support the separation. I'm talking about a different layer of separation:

`rule/cxf` -> `rule/cxf-server` & `rule/cxf-client`

What do you think? Does this kind of separation make sense?

**Comment by jianshaow** [comment]
Hi @safris, I agree with you, I'm working on it.

**Pull request closed without merging**
