### PR TITLE
Fix spring-messaging Static Deferred Attach 

### PR DESCRIPTION
**Pull request by malafeev**
#460

### CODE REVIEW

**Comment by safris** [comment]
@malafeev, can you please merge master into this PR and trigger another build?

**Comment by malafeev** [comment]
@safris merged and triggered

**Comment by safris** [comment]
@malafeev, the log for `spring-messaging` on jdk11 in the previous build shows:
```
Span: {traceId:1, spanId:2, parentId:0, operationName:"send:output"}
	Component: spring-messaging
	Tags: {component=spring-messaging, message_bus.destination=output, span.kind=producer}
	Logs: 
Span: {traceId:1, spanId:3, parentId:2, operationName:"To_testDestination"}
	Component: java-kafka
	Tags: {component=java-kafka, message_bus.destination=testDestination, span.kind=producer, peer.service=kafka}
	Logs: 
Span: {traceId:1, spanId:5, parentId:3, operationName:"receive:input"}
	Component: spring-messaging
	Tags: {component=spring-messaging, message_bus.destination=input, span.kind=consumer}
	Logs: 
Span: {traceId:1, spanId:4, parentId:3, operationName:"onMessage"}
	Component: spring-kafka
	Tags: {span.kind=consumer, component=spring-kafka}
	Logs: 
-------> Intercept [FixedRateAgentRule@kafka-request-handler-2]: public java.util.concurrent.ScheduledFuture java.util.concurrent.ScheduledThreadPoolExecutor.scheduleAtFixedRate(java.lang.Runnable,long,long,java.util.concurrent.TimeUnit)
-------> Intercept [FixedRateAgentRule@kafka-network-thread-0-ListenerName(PLAINTEXT)-PLAINTEXT-2]: public java.util.concurrent.ScheduledFuture java.util.concurrent.ScheduledThreadPoolExecutor.scheduleAtFixedRate(java.lang.Runnable,long,long,java.util.concurrent.TimeUnit)
java.lang.AssertionError: 1 spans instead of 2 of java-kafka
	at io.opentracing.contrib.specialagent.TestUtil.checkSpan(TestUtil.java:140)
	at io.opentracing.contrib.specialagent.test.spring.messaging.SpringMessagingITest.main(SpringMessagingITest.java:105)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.mojo.exec.Exec.main(Exec.java:26)
```

**Comment by malafeev** [comment]
yes, it's failing in travis all time but never on my machine with open jdk 11.0.2

**Comment by malafeev** [comment]
closing PR because it cannot be merged until spring-kafka will be fixed
https://github.com/opentracing-contrib/java-specialagent/issues/393#issuecomment-597673874

**Pull request closed without merging**
